baseurl      = "http://bradleystevanus.com/"
languageCode = "en-us"
theme        = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

enableEmoji = true

[author]
    name = "Bradley Stevanus"

[taxonomies]
    category = "categories"
    tag      = "tags"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home (set in laguages section)
    homeSubtitle = ""

    # Set a background for the homepage
    # backgroundImage = "assets/images/background.jpg"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    # There are a lot of buttons preconfigured. If you want to change them,
    # generate the buttons here: https://sharingbuttons.io
    # and add them into your own `layouts/partials/sharing-buttons.html`
    enableSharingButtons = true

    # Enables the global language menu.
    enableGlobalLanguageMenu = true

    # Toggle this option need to rebuild SCSS, requires extended version of Hugo
    # justifyContent = false  # Set "text-align: justify" to .post-content

    # Integrate Javascript files or stylesheets by adding the url to the external assets or by
    # linking local files with their path relative to the static folder, e.g. "css/styles.css"
    customCSS = []
    customJS  = []

    # Metadata mostly used in document's head
    description = "My website and blog"
    keywords = "homepage, blog"
    images = [""]

    # Colors for favicons
    [params.favicon.color]
        mask = "#1b1c1d"
        msapplication = "#1b1c1d"
        theme = "#1b1c1d"

    [params.logo]
        logoMark     = ">"
        logoText     = "$ curl https://www.bradleystevanus.com"
        logoHomeLink = "/"
        # Set true to remove the logo cursor entirely.
        # logoCursorDisabled = false
        # Set to a valid CSS color to change the cursor in the logo.
        # logoCursorColor    = "#67a2c9"
        # Set to a valid CSS time value to change the animation duration, "0s" to disable.
        # logoCursorAnimate  = "2s"

    # Commento is more than just a comments widget you can embed — 
    # it’s a return to the roots of the internet. 
    # An internet without the tracking and invasions of privacy. 
    # An internet that is simple and lightweight. 
    # An internet that is focused on interesting discussions, not ads. 
    # A better internet.
    # Uncomment this to enable Commento.
    # [params.commento]
    #   url = ""

    # Uncomment this if you want a portrait on your start page
    # [params.portrait]
    #   path     = "/img/image.jpg"
    #   alt      = "Portrait"
    #   maxWidth = "50px"

    # Social icons
    # [[params.social]]
    #     name = "twitter"
    #     url  = "https://twitter.com/"

    [[params.social]]
        name = "email"
        url  = "mailto:bradleystevanus@outlook.com"

    [[params.social]]
        name = "github"
        url  = "https://github.com/bradstevanus1/"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/brad-stevanus/"

    # [[params.social]]
    #     name = "stackoverflow"
    #     url  = "https://www.stackoverflow.com/"

[languages]
    [languages.en]
        title = "Hi, I'm Bradley Stevanus"
        homeSubtitle  = "This is my personal website and blog"
        # subtitle = "?"
        keywords = ""
        weight    = 1
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        readOtherPosts = "Read other posts"

    [languages.fr]
        title = "Bonjour, je m'appelle Bradley Stevanus"
        homeSubtitle  = "C'est mon site personnel et blog"
        # subtitle = "?"
        keywords = ""
        weight    = 2
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        readOtherPosts = "lire les autres messages"

[menu]
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"
    [[menu.main]]
        identifier = "posts"
        name       = "Posts"
        url        = "posts/"
